env_variables:
  - &DB "${{DB}}/mm10"
  - &SCRIPTS "${{SCRIPTS}}"

seq_info_format:
- ";"
- project
- idir
- ibams
#- seq_order
#- config_id
seq_order:
  - 1
  - 2
  - 3
config_ids: 
  - DEFAULT


DEFAULT:
  cmd_fusion_order: ['1', 2,3,"STAT"]
  cmd_name: atac_merge.pe.cmd.txt
  log_name: log
  outdir : atac_merge_pe
  data_name: data.yaml
  order:
    - merge_bam
    - to_fragment
    - all
    - ocr
    - nucleosome
    - frip_cal_all
    - frip_cal_ocr
    - linkbw
    - metagene_nuc
    - frag_len

  order_stat: 
    - stat_log_all
    - stat_log_ocr
    - stat_echo

  
  workflow:

    merge_bam:
      need: true 
      path: ""
      outdir: "1.merged_bam"
      father:
        idir: 
          - raw
          - idir
        ibams:
          - raw
          - ibams
      variables:
        obam: "{outdir}/{project}.bam"
        threads: 8
        obed: "{outdir}/{project}.fragment.bed"
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bamtobedpe.sh"
        
      params:
        blank:
          - "cd {idir} "
          - "&& echo {ibams} | tr , ' ' | xargs samtools merge -@ {threads} {obam} "
      outparams:
        obam: "{obam}"
        obed: "{obed}"

    to_fragment:
      need: true
      path: " "
      outdir: 2.fragments
      father:
        ibam:
          - merge_bam
          - obam 
      variables:
        obed: "{outdir}/{project}.fragment.bed"
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bamtobedpe.sh"
      params:
        blank:
          - "bash {script} {ibam} 8 | sort -k1,1 -k2,2n | awk 'BEGIN{{OFS=\"\\t\"}}{{$2=$2+4;$3=$3-5;print $0}}'  > {obed}"
      outparams:
        obed: "{obed}"

    all:
      need: true 
      path: " "
      outdir: "3.allLen/{project}"
      father: 
        ibed:
          - to_fragment
          - obed
      variables:
        all_bed: "{outdir}/{project}.all.fragment.bed"
        thre: 250
        sp: mm
        obdg: "{outdir}/{project}.all_treat_pileup.bdg"
        opeaks: "{outdir}/{project}.all_peaks.narrowPeak"
        olog: "{outdir}/{project}.all.macs2.log"
        obw: "{outdir}/{project}.all.bw"
        db: *DB
        chromSize: "{db}/mm10_main.chrom.sizes"
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_fc.sh"
        ofcbw: "{outdir}/{project}.all.fc.bw"
      params:
        blank: 
          - "cat {ibed} | awk -v l={thre} 'BEGIN{{OFS=\"\\t\"}}{{mean=int(($2+$3)/2);$2=mean-l/2;$3=mean+l/2;print $0}}' | grep -v chrM > {all_bed} &&"
          - "macs2 callpeak -f BEDPE -g {sp} --SPMR -B -q 0.05 --keep-dup 1  -n {project}.all --outdir  {outdir} -t {all_bed} 2>&1 | tee {olog} && "
          - "echo \"########## macs2 call peak  {project} done \" &&"
          - "sort -k1,1 -k2,2n {obdg} > {obdg}.tmp && "
          - "bedGraphToBigWig {obdg}.tmp {chromSize} {obw} && "
          - "rm -f  {obdg}.tmp &&"
          - "rm -f {obdg} &&"
          - "bash {script} {obw} {chromSize} {ofcbw} "
      outparams:
        ofrag: "{all_bed}"
        opeaks: "{opeaks}"
        olog: "{olog}"
        obw: "{obw}"
        ofcbw: "{ofcbw}"

    ocr: 
      need: true 
      path: " "
      outdir: "4.ocr/{project}"
      father: 
        ibed:
          - to_fragment
          - obed
      variables:
        ocr_bed: "{outdir}/{project}.ocr.fragment.bed"
        thre: 140
        sp: mm
        obdg: "{outdir}/{project}.ocr_treat_pileup.bdg"
        opeaks: "{outdir}/{project}.ocr_peaks.narrowPeak"
        olog: "{outdir}/{project}.ocr.macs2.log"
        obw: "{outdir}/{project}.ocr.bw"
        db: *DB
        chromSize: "{db}/mm10_main.chrom.sizes"
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_fc.sh"
        ofcbw: "{outdir}/{project}.ocr.fc.bw"
      params:
        blank: 
          - "cat {ibed} | awk '$3-$2 < {thre}' | grep -v chrM > {ocr_bed} &&"
          - "macs2 callpeak -f BEDPE -g {sp} --SPMR -B -q 0.05 --keep-dup 1  -n {project}.ocr --outdir  {outdir} -t {ocr_bed} 2>&1 | tee {olog} && "
          - "echo \"########## macs2 call peak  {project} done \" &&"
          - "sort -k1,1 -k2,2n {obdg} > {obdg}.tmp && "
          - "bedGraphToBigWig {obdg}.tmp {chromSize} {obw} && "
          - "rm -f  {obdg}.tmp &&"
          - "rm -f {obdg} &&"
          - "bash {script} {obw} {chromSize} {ofcbw} "
      outparams:
        ofrag: "{ocr_bed}"
        opeaks: "{opeaks}"
        olog: "{olog}"
        obw: "{obw}"
        ofcbw: "{ofcbw}"

    nucleosome:
      need: true 
      path: " "
      outdir: "5.nuc/{project}"
      father: 
        ibed:
          - to_fragment
          - obed
      variables:
        nuc_bed: "{outdir}/{project}.nuc.fragment.bed"
        thre: 180
        sp: mm
        obdg: "{outdir}/{project}.nuc_treat_pileup.bdg"
        opeaks: "{outdir}/{project}.nuc_peaks.narrowPeak"
        olog: "{outdir}/{project}.nuc.macs2.log"
        obw: "{outdir}/{project}.nuc.bw"
        db: *DB
        chromSize: "{db}/mm10_main.chrom.sizes"
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_fc.sh"
        ofcbw: "{outdir}/{project}.nuc.fc.bw"
      params:
        blank: 
          - "cat {ibed} | awk '$3-$2 > {thre}' | grep -v chrM > {nuc_bed} &&"
          - "macs2 callpeak -f BEDPE -g {sp} --SPMR -B -q 0.05 --keep-dup 1  -n {project}.nuc --outdir  {outdir} -t {nuc_bed}  2>&1 | tee {olog} && "
          - "echo \"##### macs2 call peak done \" &&" 
          - "sort -k1,1 -k2,2n {obdg} > {obdg}.tmp && "
          - "bedGraphToBigWig {obdg}.tmp {chromSize} {obw} && "
          - "rm -f  {obdg}.tmp &&"
          - "rm -f {obdg} &&"
          - "bash {script} {obw} {chromSize} {ofcbw} "
      outparams:
        ofrag: "{nuc_bed}"
        opeaks: "{opeaks}"
        olog: "{olog}"
        obw: "{obw}"
        ofcbw: "{ofcbw}"
      
    frip_cal_ocr:
      need: true
      cmd_part: 2
      path: " "
      outdir: "4.ocr/{project}"
      father: 
        ipeaks:
          - ocr
          - opeaks
        ibed:
          - ocr
          - ofrag
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/peak_stat.py"
        oname: "{outdir}/{project}.{part}.stat"
      params:
        blank:
          - "python {script} {ipeaks} {ibed} {oname} &" 
      outparams:
        oname: "{oname}"

    frip_cal_all:
      need: true
      cmd_part: 2
      path: " "
      outdir: "3.allLen/{project}"
      father: 
        ipeaks:
          - all
          - opeaks
        ibed:
          - all
          - ofrag
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/peak_stat.py"
        oname: "{outdir}/{project}.{part}.stat"
      params:
        blank:
          - "python {script} {ipeaks} {ibed} {oname} &" 
      outparams:
        oname: "{oname}"

    linkbw:
      need: true 
      outdir: "6.Bw"
      father:
        ocr_bw:
          - ocr
          - obw
        ocr_fcbw:
          - ocr
          - ofcbw
      params:
        blank:
          - "ln -snf {ocr_bw} {outdir} &&"
          - "ln -snf {ocr_fcbw} {outdir} "
    
    metagene_nuc:
      need: true 
      cmd_part: 3
      path: " "
      outdir: "7.metagene_nuc"
      father:
        ibw:
          - nucleosome
          - ofcbw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_summary_bed_bins.py"
        db: *DB
        bed: "{db}/mm10.refGene.main.bed"
        oname: "{outdir}/{project}.nuc.tsv"

      params:
        "python ": "{script}"
        -b: "{bed}"
        -w: "{ibw}"
        -n: "100"
        "-5": 2000
        "-3": 2000
        "--5bins": 100
        "--3bins" : 100
        -o: "{oname}"
        blank: 
          - " &"
      outparams:
        oname: "{oname}"

    frag_len:
      need: true
      outdir: 8.frag_len
      father:
        raw_frag:
          - to_fragment
          - obed
        nuc_frag:
          - nucleosome
          - ofrag
      variables:
        raw_stat: "{outdir}/{project}.raw.length_distribution.txt"
        nuc_stat: "{outdir}/{project}.nuc.length_distribution.txt"
      params:
        blank:
          - "cat {raw_frag} | awk '{{print $3-$2}}' | sort  | uniq -c > {raw_stat} &&"
          - "cat {nuc_frag} | awk '{{print $3-$2}}' | sort  | uniq -c > {raw_stat} "


  stat: 
    stat_log_ocr:
      need: true 
      outdir: "0.stat"
      path: " "
      iparams_list:
        macs:
          - ocr
          - olog
          - ","
        peaks:
          - frip_cal_ocr
          - oname
          - ","
        projects:
          - raw
          - project
          - ","
      variables:
        script_dir: *SCRIPTS
        script: "{script_dir}/extract_log.py"
        oname: "{outdir}/0.basic.ocr.stats"
      params:
        "python" : "{script}"
        "-m": "{macs}"
        "-l": "{peaks}"
        "-p": "{projects}"
        "-o": "{oname}"
      outparams:
        oname: "{oname}"

    stat_log_all:
      need: true 
      outdir: "0.stat"
      path: " "
      iparams_list:
        macs:
          - all
          - olog
          - ","
        peaks:
          - frip_cal_all
          - oname
          - ","
        projects:
          - raw
          - project
          - ","
      variables:
        script_dir: *SCRIPTS
        script: "{script_dir}/extract_log.py"
        oname: "{outdir}/0.basic.all.stats"
      params:
        "python" : "{script}"
        "-m": "{macs}"
        "-l": "{peaks}"
        "-p": "{projects}"
        "-o": "{oname}"
      outparams:
        oname: "{oname}"

    stat_echo:
      need: true 
      outdir: "0.stat"
      path: " "
      variables:
        oname: "{outdir}/datainfo.csv"
      iparams_list:
        bam: 
          - merge_bam
          - obam
          - ","
        ocrpeak:
          - ocr
          - opeaks
          - ","     
        bw:
          - ocr
          - obw
          - ","
        fcbw:
          - ocr
          - ofcbw
          - ","
        fragments:
          - to_fragment
          - obed
          - ","
        ocr_frag:
          - ocr
          - ofrag
          - ","
        project:
          - raw
          - project
          - ","
      params:
        blank:
          - "echo '' > {oname} "
          - "&& echo project,{project} >> {oname}"
          - "&& echo bam,{bam} >> {oname}"
          - "&& echo bw,{bw} >> {oname}"
          - "&& echo fcbw,{fcbw} >> {oname}"
          - "&& echo ocrpeak,{ocrpeak} >> {oname}"
          - "&& echo ocr_frag,{ocr_frag} >> {oname}"
          - "&& echo fragment,{fragments} >> {oname}"


       