seq_info_format:
- ','
- project
- seq1
- seq2
#- seq_order
#- config_id
seq_order:
  - 1
  - 2
  - 3
config_ids: 
  - DEFAULT

DEFAULT:
  cmd_fusion_order: ['1', 2,"STAT"] #Keep "STAT" in, for stat workflows
  cmd_name: tas.cmd
  log_name: tas.log
  outdir : tasout
  data_name: data.yaml

  order:
    - helloworld

  order_stat: []


  workflow:
        helloworld:
          need: true
          variables: {}
          functions: {}
          funcitions_last: {}
          father: {}
          outparams: {}
          params:
            ' ': '" hello world"'
          path: echo
  
  stat: {}