env_variables:
  - &DB "${{DB}}/hg38"
  - &SCRIPTS "${{SCRIPTS}}"

seq_info_format:
- ","
- project
- seq1
- seq2
#- seq_order
#- config_id
seq_order:
  - 1
  - 2
  - 3
config_ids: 
  - DEFAULT

DEFAULT:
  cmd_fusion_order: ['1', 2,3,"STAT"]
  cmd_name: chiseq.cmd.txt
  log_name: log
  outdir : dataset
  data_name: data.yaml
  order:
    - fastqc
    - trim_pe
    - bowtie2
    - sort_and_markdup
    - to_fragment
    - peakcalling14
    - peakcalling2
    - toBwfrompeakcalling
    - bwfc
    - ceas
    - frip_cal
    - bw_summary
    - metagene
  
  order_stat: 
    - stat_log
    - stat_echo

  
  workflow:
    fastqc:
      need: true
      outdir: 1.trimed
      path: fastqc
      father:
        iseq1:
          - raw
          - seq1
        iseq2:
          - raw
          - seq2
      params:
        -t: 10
        -o: "{outdir}"
        blank: 
          - "{iseq1}"
          - "{iseq2}"
      outparams:
        outdir: "{outdir}"
   
    trim_pe:
      path: trim_galore
      check_paths: []
      cmd_part: '1'
      father:
        iseq1:
        - raw
        - seq1
        iseq2:
        - raw
        - seq2
      need: true
      outdir: 1.trimed
      variables:
        log: "{outdir}/{project}.{part}.log"
      outparams:
        oseq1: "{outdir}/{project}_val_1.fq.gz"
        oseq2: "{outdir}/{project}_val_2.fq.gz"
        example: '{project}/hello'
      params:
        ' ': '{iseq1}  {iseq2}'
        --fastqc: ''
        --fastqc_args: '"--threads 8 "'
        --length: '20'
        --paired: ''
        --quality: '20'
        -o: '{outdir}'
        --cores: 2
        --basename: "{project}"
        blank:
          - " 2>&1 | tee {log} "    

    bowtie2:
      need: true
      outdir: 2.mapping
      path: ""
      father: 
        iseq1:
          - trim_pe
          - oseq1
        iseq2:
          - trim_pe
          - oseq2
      variables:
        olog: "{outdir}/{project}.mapping.log"
        osam: "{outdir}/{project}.sam"
        obam: "{outdir}/{project}.bam"
        threads: 10
        db: *DB
      params:
        blank:
          - "bowtie2 -q -x {db}/hg38_main --no-discordant --threads {threads} -1 {iseq1} -2 {iseq2} -S {osam} 2>&1 | tee {olog} "
          - " && samtools view --threads {threads} -f 0x2 -q 30 -o {obam} {osam} "
          - " && rm {osam} "
      outparams:
        osam: "{osam}"
        obam: "{obam}"
        olog: "{olog}"
          
    sort_and_markdup: 
      need: true
      path: " "
      outdir: 3.cleanBam
      father:
        ibam:
          - bowtie2
          - obam
      variables:
        sort_bam: "{outdir}/{project}.sort"
        fixmate: "{outdir}/{project}.fix"
        fixsort: "{outdir}/{project}.fix.sort"
        cleanbam: "{outdir}/{project}_clean.bam"
      
      params:
        blank:
          - "sambamba markdup -r -t 10 {ibam} {sort_bam} &&"
          - "sambamba sort -t 10 {sort_bam} -o {cleanbam} &&"
          - "rm {sort_bam} "
    
      
      outparams:
        obam: "{cleanbam}"

    to_fragment:
      need: true
      path: " "
      outdir: 3.cleanBam
      father:
        ibam:
          - sort_and_markdup
          - obam 
      variables:
        obed: "{outdir}/{project}.fragment.bed"
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bamtobedpe.sh"
      params:
        blank:
          - "bash {script} {ibam} 8 | sort -k1,1 -k2,2n > {obed}"
      outparams:
        obed: "{obed}"

    peakcalling14:
      need: true 
      path: "macs14 "
      outdir: "4.peakcalling/{project}"
      father:
        ibam:
          - sort_and_markdup
          - obam
      cmd_part: 2
      variables:
        olog: "{outdir}/{project}.macs14.log"
      params:
        -f: BAM
        -g: hs
        -p: 1e-5
        --keep-dup: 1
        --nomodel: " "
        --shiftsize: 73
        -n: "{outdir}/{project}"
        -t: "{ibam}"
        blank:
          - "2>&1 | tee {olog} &"
      outparams:
        opeaks: "{outdir}/{project}_peaks.bed"
        osummits: "{outdir}/{project}_summits.bed"
        obdg: "{outdir}/{project}_treat_pileup.bdg"
        olog: "{olog}"
      
    peakcalling2:
      need: true
      path: "macs2 callpeak"
      outdir: 4.peakcalling
      father:
        ibam:
          - sort_and_markdup
          - obam
      cmd_part: 2
      variables:
        olog: "{outdir}/{project}/{project}.macs2.log"
      params:
        -f: BAMPE
        --SPMR: " "
        -g: hs
        -B: " "
        -q: 0.05
        --keep-dup: 1
        --nomodel: " "
        --extsize: 147
        -n: "{project}"
        --outdir: "{outdir}/{project}"
        -t: "{ibam}"
        blank:
          - "2>&1 | tee {olog} &"
    
      outparams:
        opeaks: "{outdir}/{project}/{project}_peaks.narrowPeak"
        osummits: "{outdir}/{project}/{project}_summits.bed"
        obdg: "{outdir}/{project}/{project}_treat_pileup.bdg"
        olog: "{olog}"
    
    toBwfrompeakcalling:
      need: true
      path: " "
      outdir: "4.peakcalling/{project}"
      cmd_part: 2
      father:
        ibdg: 
          - peakcalling2
          - obdg
      variables:
        obw: "{outdir}/{project}.bw"
        db: *DB
        chromSize: "{db}/hg38_main.chrom.sizes"
      params:
        blank: 
          - "sort -k1,1 -k2,2n {ibdg} > {ibdg}.tmp "
          - "&& bedGraphToBigWig {ibdg}.tmp {chromSize} {obw} "
          - "&& rm -f  {ibdg}.tmp &"
      outparams:
        obw: "{obw}"

    bwfc:
      need: true 
      path: " "
      outdir: "5.Bw"
      cmd_part: 2
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_fc.sh"
        db: *DB
        chromSize: "{db}/hg38_main.chrom.sizes"
        obw: "{outdir}/{project}.fc.bw"
      params:
        blank:
          - "bash {script} {ibw} {chromSize} {obw}"
      outparams:
        obw: "{obw}"

    
    ceas:
      need: true
      path: ceasBW
      outdir: 6.ceas
      cmd_part: 2
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
        ibed: 
          - peakcalling2
          - osummits
      variables:
        oname: "{outdir}/{project}/{project}"
        bisize: 2000
        db: *DB
        chromsize: "{db}/hg38_main.chrom.sizes"
      functions:
        - "mkdirs('{outdir}/{project}')"
      params:
        -g: "{db}/hg38.refGene.main.sqlite3"
        -l: "{chromsize}"
        --dump: " "
        --bg: " "
        --bisizes: "{bisize}"
        -w: "{ibw}"
        -b: "{ibed}"
        --name: "{oname}"
      outparams:
        ogene: "{oname}_dump_gene.txt"
        oTSS: "{oname}_dump_TSS.txt"
        oTTS: "{oname}_dump_TTS.txt"
        opdf: "{oname}.pdf"

    frip_cal:
      need: true
      cmd_part: 2
      path: " "
      outdir: "4.peakcalling/{project}"
      father: 
        ipeaks:
          - peakcalling14
          - opeaks
        ibam:
          - sort_and_markdup
          - obam
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/peak_stat.py"
        oname: "{outdir}/{project}.{part}.stat"
      params:
        blank:
          - "python {script} {ipeaks} {ibam} {oname} &" 
      outparams:
        oname: "{oname}"
    

    bw_summary:
      need: true 
      cmd_part: 3
      path: ""
      outdir: "7.bw_summary"
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_summary_bed.py"
        db: *DB
        bed: "{db}/hg38.refGene.main.promoter_2k.bed"
        osummary: "{outdir}/{project}.summary"
      params:
        blank:
          - "python {script} {bed} {ibw} {osummary} &"
      outparams:
        osummary: "{osummary}"
      
    metagene:
      need: true 
      cmd_part: 3
      path: " "
      outdir: "8.metegene"
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_summary_bed_bins.py"
        db: *DB
        bed: "{db}/hg38.refGene.main.bed"
        oname: "{outdir}/{project}.tsv"

      params:
        "python ": "{script}"
        -b: "{bed}"
        -w: "{ibw}"
        -n: "100"
        "-5": 2000
        "-3": 2000
        "--5bins": 100
        "--3bins" : 100
        -o: "{oname}"
        blank: 
          - " &"
      outparams:
        oname: "{oname}"

    
  stat: 
    stat_log:
      need: true 
      outdir: "0.stat"
      path: " "
      iparams_list:
        bowtie2:
          - bowtie2
          - olog
          - ","
        macs:
          - peakcalling14
          - olog
          - ","
        peaks:
          - frip_cal
          - oname 
          - ","
        projects:
          - raw
          - project
          - ","
      variables:
        script_dir: *SCRIPTS
        script: "{script_dir}/extract_log.py"
        oname: "{outdir}/0.basic.stats"
      params:
        "python" : "{script}"
        "-b": "{bowtie2}"
        "-m": "{macs}"
        "-l": "{peaks}"
        "-p": "{projects}"
        "-o": "{oname}"
      outparams:
        oname: "oname"

    stat_echo:
      need: true 
      outdir: "0.stat"
      path: " "
      variables:
        oname: "{outdir}/datainfo.csv"
      iparams_list:
        bam: 
          - sort_and_markdup
          - obam
          - ","
        peak:
          - peakcalling14
          - opeaks
          - ","
        bw:
          - bwfc
          - obw
          - ","
        fragments:
          - to_fragment
          - obed
          - ","
        project:
          - raw
          - project
          - ","
      params:
        blank:
          - "echo '' > {oname} "
          - "&& echo project,{project} >> {oname}"
          - "&& echo bam,{bam} >> {oname}"
          - "&& echo bw,{bw} >> {oname}"
          - "&& echo peak,{peak} >> {oname}"
          - "&& echo fragment,{fragments} >> {oname}"

        
    


