env_variables:
  - &DB "${{DB}}/mm10"
  - &SCRIPTS "${{SCRIPTS}}"

seq_info_format:
- ";"
- project
- idir
- ibeds
#- seq_order
#- config_id
seq_order:
  - 1
  - 2
  - 3
config_ids: 
  - DEFAULT


DEFAULT:
  cmd_fusion_order: ['1', 2,3,"STAT"]
  cmd_name: atac_merge.pe.cmd.txt
  log_name: log
  outdir : 2.mergedSamples
  data_name: data.yaml
  order:
    - merge_bed
    - cutsites
    - all
    - ocr
    - nucleosome
    - frip_cal_all
    - frip_cal_ocr
    - linkbw
    - metagene_nuc
    - frag_len

  order_stat: 
    - stat_log_all
    - stat_log_ocr
    - stat_echo

  
  workflow:

    merge_bed:
      need: true 
      path: ""
      outdir: "1.merged_bed"
      father:
        idir: 
          - raw
          - idir
        ibeds:
          - raw
          - ibeds
      variables:
        threads: 8
        obed: "{outdir}/{project}.fragment.bed"
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bedtobedpe.sh"
        
      params:
        blank:
          - "cd {idir} "
          - "&& echo {ibeds} | tr , ' ' | xargs cat | sort -k1,1 -k2,2n >  {obed} "
      outparams:
        obed: "{obed}"


    peakcalling14:
      need: true 
      path: "macs14 "
      outdir: "2.peakcalling/{project}"
      father:
        ibed:
          - merge_bed
          - obed
      cmd_part: 2
      variables:
        olog: "{outdir}/{project}.macs14.log"
      params:
        blank:
          - "-f BAM -g mm -p 1e-5 --keep-dup all -n {outdir}/{project}.macs14 -t {ibed}  "
          - "2>&1 | tee {olog} "
          - "&& mv {outdir}/{project}_summits.bed {osummits}"
      outparams:
        opeaks: "{outdir}/{project}_peaks.macs14.bed"
        opeakbed: "{outdir}/{project}.macs14_peaks.bed"
        olog: "{olog}"
      
    peakcalling2:
      need: true
      path: "macs2 callpeak"
      outdir: 2.peakcalling
      father:
        ibed:
          - merge
          - obed
      cmd_part: 2
      variables:
        olog: "{outdir}/{project}/{project}.macs2.log"
        opeaks: "{outdir}/{project}/{project}.macs2_peaks.narrowPeak"
        opeakbed: "{outdir}/{project}/{project}.macs2.bed"
        osummits: "{outdir}/{project}/{project}.macs2_summits.bed"
      params:
        blank: 
          - " -f BAMPE --SPMR -g mm -B -q 0.05 --keep-dup all -n {project}.macs2 --outdir  {outdir}/{project} -t {ibed} "
          - "&& cat opeaks | cut -f 1-5 | sort -k1,1 -k2,2n > {opeakbed} "
          - " 2>&1 | tee {olog} &"
    
      outparams:
        opeaks: "{opeaks}"
        opeakbed: "{opeakbed}"
        osummits: "{osummits}"
        obdg: "{outdir}/{project}/{project}.macs2_treat_pileup.bdg"
        olog: "{olog}"
    
    toBwfrompeakcalling:
      need: true
      path: " "
      outdir: "2.peakcalling/{project}"
      cmd_part: 2
      father:
        ibdg: 
          - peakcalling2
          - obdg
      variables:
        obw: "{outdir}/{project}.bw"
        db: *DB
        chromSize: "{db}/mm10_main.chrom.sizes"
      params:
        blank: 
          - 'sort -k1,1 -k2,2n {ibdg} | grep  -e  "chr[0-9XYM]*\b"  | bedClip stdin {chromSize} {ibdg}.tmp '
          - "&& bedGraphToBigWig {ibdg}.tmp {chromSize} {obw} "
          - "&& rm -f  {ibdg}.tmp &"
      outparams:
        obw: "{obw}"

    bwfc:
      need: true 
      path: " "
      outdir: "3.Bw"
      cmd_part: 2
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_fc.sh"
        db: *DB
        chromSize: "{db}/mm10_main.chrom.sizes"
        obw: "{outdir}/{project}.fc.bw"
      params:
        blank:
          - "ln -snf {ibw} {outdir}/{project}.bw  "
          - "&& bash {script} {ibw} {chromSize} {obw} &"
      outparams:
        obw: "{obw}"

    
    ceas:
      need: true 
      path: ""
      outdir: "4.ceas"
      cmd_part: 2
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
        ibed: 
          - peakcalling2
          - opeakbed
      variables:
        oname: "{outdir}/{project}/{project}"
        bisize: 2000
        db: *DB
        chromsize: "{db}/mm10_main.chrom.sizes"
        ref: "{db}/mm10.refGene.sqlite3"
      functions:
        - "mkdirs('{outdir}/{project}')"
      params:
        blank: 
          - "ceasBW -g {ref} -l {chromsize} --dump --bg --bisizes {bisize} -w {ibw} -b {ibed} --name {oname} "
      outparams:
        ogene: "{oname}_dump_gene.txt"
        oTSS: "{oname}_dump_TSS.txt"
        oTTS: "{oname}_dump_TTS.txt"
        opdf: "{oname}.pdf"

    frip_cal:
      need: true
      cmd_part: 2
      path: " "
      outdir: "2.peakcalling/{project}"
      father: 
        ipeaks:
          - peakcalling2
          - opeakbed
        ibed:
          - merge
          - obed
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/peak_stat.py"
        oname: "{outdir}/{project}.{part}.stat"
      params:
        blank:
          - "python {script} {ipeaks} {ibed} {oname}"
      outparams:
        oname: "{oname}"
    

    
  stat: 
    stat_log:
      need: true 
      outdir: "0.stat"
      path: " "
      iparams_list:
        macs:
          - peakcalling2
          - olog
          - ","
        peaks:
          - frip_cal
          - oname 
          - ","
        projects:
          - raw
          - project
          - ","
      variables:
        script_dir: *SCRIPTS
        script: "{script_dir}/extract_log.py"
        oname: "{outdir}/0.basic.stats"
      params:
        "python" : "{script}"
        "-m": "{macs}"
        "-l": "{peaks}"
        "-p": "{projects}"
        "-o": "{oname}"
      outparams:
        oname: "oname"
    


