env_variables:
  - &DB "${{DB}}/mm10"
  - &SCRIPTS "${{SCRIPTS}}"

seq_info_format:
- " "
- project
- seq1
#- seq_order
#- config_id
seq_order:
  - 1
  - 2
  - 3
config_ids: 
  - DEFAULT

DEFAULT:
  cmd_fusion_order: ['1', 2,3,"STAT"]
  cmd_name: chipseq.cmd.txt
  log_name: log
  outdir : 1.chipseqout
  data_name: data.yaml
  order:
    - get_fq
    - fastqc
    - trim_se
    - bowtie2
    - to_bam
    - sort_and_markdup
    - peakcalling2
    - toBwfrompeakcalling
    - bwfc
    - ceas
    - frip_cal
    - bw_summary
    - metagene
  
  order_stat: 
    - stat_log

  
  workflow:
    get_fq:
      need: false
      outdir: raw
      path: ""
      father:
        iseq1:
          - raw
          - seq1
      variables:
        oseq1: "{outdir}/{project}.SE.fq.gz"
      params:
        blank:
          - "echo {iseq1} | tr , ' ' |xargs cat > {oseq1}"
      outparams:
        seq1: "{oseq1}"
          
    fastqc:
      need: false
      outdir: 1.trimed
      path: fastqc
      father:
        iseq1:
          - get_fq
          - seq1
      params:
        -t: 10
        -o: "{outdir}"
        blank: 
          - "{iseq1}"
      outparams:
        outdir: "{outdir}"

    trim_se:
      need: true
      path: trim_galore
      outdir: 1.trimed
      check_paths: []
      cmd_part: "1"
      father:
        iseq:
          - get_fq
          - seq1 
      variables:
        log: "{outdir}/{project}.{part}.log"
      outparams:
        oseq1: "{outdir}/{project}_trimmed.fq(.gz)"
      params:
        ' ': '{iseq1} '
        --fastqc: ''
        --fastqc_args: '"--threads 8 "'
        --length: '20'
        --quality: '20'
        -o: '{outdir}'
        --cores: 2
        --basename: "{project}"
        blank:
          - "| tee {log} 2>&1 "

    trim_pe:
      path: trim_galore
      check_paths: []
      cmd_part: '1'
      father:
        iseq1:
        - get_fq
        - seq1
        iseq2:
        - get_fq
        - seq2
      need: false
      outdir: 1.trimed
      variables:
        log: "{outdir}/{project}.{part}.log"
      outparams:
        oseq1: "{outdir}/{project}_val_1.fq.gz"
        oseq2: "{outdir}/{project}_val_2.fq.gz"
        example: '{project}/hello'
      params:
        ' ': '{iseq1}  {iseq2}'
        --fastqc: ''
        --fastqc_args: '"--threads 8 "'
        --length: '20'
        --paired: ''
        --quality: '20'
        -o: '{outdir}'
        --cores: 2
        --basename: "{project}"
        blank:
          - "| tee {log} 2>&1 "
      

    bowtie2:
      need: true
      outdir: 2.mapping
      path: bowtie2
      father: 
        iseq1:
          - trim_pe
          - oseq1
      variables:
        olog: "{outdir}/{project}.mapping.log"
        osam: "{outdir}/{project}.sam"
        db: *DB
      params:
        -q: " "
        -x: "{db}/mm10_main"
        --no-discordant: " "
        --threads: 10
        -q: " "
        -x: "{iseq1}"
        -S: "{osam}"
        blank:
          - "2>&1 | tee {olog} "
      outparams:
        osam: "{osam}"
        olog: "{olog}"
      
    to_bam:
      need: true
      path: "samtools view"
      outdir: 3.Bam
      father: 
        isam:
          - bowtie2
          - osam
      variables:
        obam: "{outdir}/{project}.bam"
      params:
        --threads: 12
        -f: "0x2" #filter out reads un-paired and can't mapping to genome
        #-q: 10 ## for repeats, turn this off, becaust their poor mapq
        -o: "{obam}"
        " ": "{isam}"
      
      outparams:
        obam: "{obam}"
    
    sort_and_markdup: 
      need: true
      path: " "
      outdir: 4.cleanBam
      father:
        ibam:
          - to_bam
          - obam
      variables:
        sort_bam: "{outdir}/{project}.sort"
        fixmate: "{outdir}/{project}.fix"
        fixsort: "{outdir}/{project}.fix.sort"
        cleanbam: "{outdir}/{project}_clean.bam"
      
      params:
        blank:
          - "sambamba markdup -r -t 10 {ibam} {sort_bam} &&"
          - "sambamba sort -t 10 {sort_bam} -o {cleanbam} &&"
          - "rm {sort_bam} "
    
      
      outparams:
        obam: "{cleanbam}"

    peakcalling14:
      need: true 
      path: "macs14 "
      outdir: "5.peakcalling/{project}"
      father:
        ibam:
          - sort_and_markdup
          - obam
      cmd_part: 2
      variables:
        olog: "{outdir}/{project}.macs14.log"
      params:
        -f: BAM
        -g: hs
        -p: 1e-5
        --keep-dup: 1
        -n: "{outdir}/{project}"
        -t: "{ibam}"
        blank:
          - "2>&1 | tee {olog} &"
      outparams:
        opeaks: "{outdir}/{project}_peaks.bed"
        osummits: "{outdir}/{project}_summits.bed"
        obdg: "{outdir}/{project}_treat_pileup.bdg"
        olog: "{olog}"
      
    peakcalling2:
      need: true
      path: "macs2 callpeak"
      outdir: "5.peakcalling/{project}"
      father:
        ibam:
          - sort_and_markdup
          - obam
      cmd_part: 2
      variables:
        olog: "{outdir}/{project}.macs2.log"
        opeaks: "{outdir}/{project}_peaks.narrowPeak"
        opeakbed: "{outdir}/{project}_peaks.bed"
      params:
        -f: BAM
        --SPMR: " "
        -g: mm
        -B: " "
        -q: 0.05
        --keep-dup: 1
        -n: "{project}"
        --outdir: "{outdir}"
        -t: "{ibam}"
        blank:
          - "2>&1 | tee {olog} "
          - "&& cat {opeaks} | cut -f 1-4,7 > {opeakbed} &"
    
      outparams:
        opeaks: "{outdir}/{project}_peaks.narrowPeak"
        opeakbed: "{opeakbed}"
        osummits: "{outdir}/{project}_summits.bed"
        obdg: "{outdir}/{project}_treat_pileup.bdg"
        olog: "{olog}"
    
    toBwfrompeakcalling:
      need: true
      path: " "
      outdir: "6.BW"
      cmd_part: 2
      father:
        ibdg: 
          - peakcalling2
          - obdg
      variables:
        obw: "{outdir}/{project}.bw"
        db: *DB
        chromSize: "{db}/mm10_main.chrom.sizes"
      params:
        blank: 
          - 'sort -k1,1 -k2,2n {ibdg} | grep  -e  "chr[0-9XYM]*\b"  > {ibdg}.tmp '
          - "&& bedGraphToBigWig {ibdg}.tmp {chromSize} {obw} "
          - "&& rm -f  {ibdg}.tmp &"
      outparams:
        obw: "{obw}"

    bwfc:
      need: true 
      path: " "
      outdir: "3.Bw"
      cmd_part: 2
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_fc.sh"
        db: *DB
        chromSize: "{db}/mm10_main.chrom.sizes"
        obw: "{outdir}/{project}.fc.bw"
      params:
        blank:
          - "bash {script} {ibw} {chromSize} {obw}"
      outparams:
        obw: "{obw}"


    ceas:
      need: true 
      path: ceasBW
      outdir: "7.ceas"
      cmd_part: 2
      father:
        ibw:
          - toBwfrompeakcalling
          - obw
        ibed: 
          - peakcalling2
          - opeakbed
      variables:
        oname: "{outdir}/{project}/{project}"
        bisize: 2000
        db: *DB
        chromsize: "{db}/mm10_main.chrom.sizes"
      functions:
        - "mkdirs('{outdir}/{project}')"
      params:
        -g: "{db}/mm10.refGene.sqlite3"
        -l: "{chromsize}"
        --dump: " "
        --bg: " "
        --bisizes: "{bisize}"
        -w: "{ibw}"
        -b: "{ibed}"
        --name: "{oname}"
      outparams:
        ogene: "{oname}_dump_gene.txt"
        oTSS: "{oname}_dump_TSS.txt"
        oTTS: "{oname}_dump_TTS.txt"
        opdf: "{oname}.pdf"

    frip_cal:
      need: true
      cmd_part: 2
      path: " "
      outdir: "5.peakcalling/{project}"
      father: 
        ipeaks:
          - peakcalling2
          - opeakbed
        ibam:
          - sort_and_markdup
          - obam
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/peak_stat.py"
        oname: "{outdir}/{project}.{part}.stat"
      params:
        blank:
          - "python {script} {ipeaks} {ibam} {oname}"
      outparams:
        oname: "{oname}"
    

    bw_summary:
      need: true 
      cmd_part: 3
      path: ""
      outdir: "8.bw_summary"
      father:
        ibw:
          - bwfc
          - obw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_summary_bed.py"
        db: *DB
        bed: "{db}/mm10.refGene.main.promoter_2k.bed"
        osummary: "{outdir}/{project}.summary"
      params:
        blank:
          - "python {script} {bed} {ibw} {osummary} &"
      outparams:
        osummary: "{osummary}"
      
    metagene:
      need: true 
      cmd_part: 3
      path: " "
      outdir: "9.metegene"
      father:
        ibw:
          - bwfc
          - obw
      variables:
        scripts_dir: *SCRIPTS
        script: "{scripts_dir}/bw_summary_bed_bins.py"
        db: *DB
        bed: "{db}/mm10.refGene.main.bed"
        oname: "{outdir}/{project}.tsv"

      params:
        "python ": "{script}"
        -b: "{bed}"
        -w: "{ibw}"
        -n: "100"
        -o: "{oname}"
        blank: 
          - " &"
      outparams:
        oname: "{oname}"

    
  stat: 
    stat_log:
      need: true 
      outdir: "0.stat"
      path: " "
      iparams_list:
        bowtie2:
          - bowtie2
          - olog
          - ","
        macs:
          - peakcalling2
          - olog
          - ","
        peaks:
          - frip_cal
          - oname 
          - ","
        projects:
          - raw
          - project
          - ","
      variables:
        script_dir: *SCRIPTS
        script: "{script_dir}/extract_log.py"
        oname: "{outdir}/0.basic.stats"
      params:
        "python" : "{script}"
        "-b": "{bowtie2}"
        "-m": "{macs}"
        "-l": "{peaks}"
        "-p": "{projects}"
        "-o": "{oname}"
      outparams:
        oname: "oname"
    


