rnaseq: rnaseq.yaml
rnaseq_featurecounts: rnaseq_featureCounts.yaml
rnaseq_repeats: rnaseq_repeats.yaml


chipseq: chipseq_v3.1.yaml
chipseq_merge: chipseq_merge.yaml
chipseqtf: chipseq_TF_v2.yaml
chipseqtf_merge: chipseq_TF_merge.yaml

mnase: mnase.yaml

blank: blank.yaml
wgbs: wgbs_pe.yaml
wgbs_pe: wgbs_pe.yaml
wgbs_se: wgbs_se.yaml

default: blank.yaml