### Config file for https://github.com/yang-dongxu/totalDataAnalysisWorkflow
### This config contain two part: seq_info_format to process the raw data info from -bf params in main function, and config for different work steps
### Only two type key should to be contained in main envrionment: seq_info_format, and config/-id
### For each configid, it should contain attributes below:
### cmd_fusion_order: to define the order to output cmd
### cmd_name and log_name: output bash script name 
### order: how to perform function defined in workflow
### order_stat: how to perform function defined in workflow_batch
### workflow: define the functions need to perform on each project seperately, {project} is a bulid variable in this part
### workflow_stat: define the functions need to perform on all projects together, or exclude some projects. 

##### for config under each part of workflow, the key is the part name display in log, and it may contains attributes below:
####### check_path: optional, assert path is exist, otherwise throw an exception an break out
####### cmd_part: which part of cmd it generates
####### father: it defines the attribute this function should get from others, in the format of {name in this function:[source,name in source function]}
####### need: if turuns false, the cmd of this part will generate as comment
####### path: how to excute this function
####### outdir: optional, define the path to save output of this function, but you still define this in params
####### variables: optional, can define some variables used in functions, params, and outparams
####### params: exact params transfer to path, can use variables {project}, {outdir}, and others defined in variables part, for position specific ones, you can provide them in list format which will set at last, while named_params can be provided in a dict
####### outparams: attributes can transfer to other functions is asked.




seq_info_format:
- ','
- project
- seq1
- seq2
#- seq_order
#- config_id
seq_order:
  - 1
  - 2
  - 3
  - last
config_ids: 
  - DEFAULT
DEFAULT:
  cmd_fusion_order: ['1','2',"STAT"]
  cmd_name: cmd
  log_name: log
  data_name: data.yaml
  order:
    - trim
    - STAR
    - toBwfrombam
    - featureCounts
    - set_featureCounts_out
  order_stat: 
    - star_log
    - normalize_expression
  outdir: rnaseq
  workflow:
    trim:
      check_paths: []
      cmd_part: '1'
      father:
        iseq1:
        - raw
        - seq1
        iseq2:
        - raw
        - seq2
      need: true
      outdir: trimed
      outparams:
        example: '{project}/hello'
      params:
        ' ': '{iseq1} {iseq2}'
        --fastqc: ''
        --fastqc_args: '"--threads 8 "'
        --length: '20'
        --paired: ''
        --quality: '20'
        -o: '{outdir}'
      path: trim_galore
      variables: 
        hello: "hello"

    STAR:
      path: STAR
      check_paths: []
      cmd_part: '1'
      father:
        iseq1:
        - trim
        - oseq1
        iseq2:
        - trim
        - oseq2
      need: true
      outdir: star

      variables:
        outprefix: "{outdir}/{project}/{project}_"

      outparams:
        obam_sorted: "{outprefix}Aligned.sortedByCoord.out.bam"
        ologfinalout: "{outprefix}Log.final.out"
        ologout: "{outprefix}Log.out"
        ologprogressout: "{outprefix}Log.progress.out"
        osj: "{outprefix}SJ.out.tab"
      params:
        --genomeDir: /mnt/Storage2/home/zengshiyang/DB/STAR/hg38
        --outFileNamePrefix: '{outprefix}'
        --outFilterMultimapNmax: '10' ## default value, for repeats, set this num to 500
        --outSAMattributes: NH HI NM MD XS AS
        --outSAMtype: BAM SortedByCoordinate
        --readFilesCommand: zcat
        --readFilesIn: '{iseq1}  {iseq2}'
        --runThreadN: '10'

    toBwfrombam:
      need: true
      path: " "
      outdir: "Bw_bam"
      cmd_part: '2'
      father: 
        ibam:
          - STAR
          - obam_sorted
      variables:
        obw: "{outdir}/{project}.bw"
      params:
        blank:
          - "samtools index -b -@ 10 {ibam}  {ibam}.bai \n"
          - "bamCoverage --samFlagExclude 12 --normalizeUsingRPKM -b {ibam} -o {obw} -p 10  \n"
      outparams:
        obw: "{obw}"
    
    featureCounts:
      check_paths: []
      cmd_part: '1'
      father:
        ibam:
        - STAR
        - obam_sorted
      functions:
        - mkdirs("{outputpath}")
      need: true
      outdir: features
      outparams:
        oname: '{oname}'
      params:
        ' ': '{ibam}'
        --fracOverlap: '0.1'
        --fraction: ' '
        -B: ' '
        -M: ' '
        -O: ' '
        -T: '10'
        -a: /mnt/Storage2/home/zengshiyang/DB/refGene/hg38/hg38.refGene.gtf
        -g: gene_id
        -o: '{oname}'
        -p: ' '
      path: featureCounts
      variables:
        outputpath: '{outdir}/{project}'
        oname: "{outputpath}/{project}_featurecounts"
     
    
    set_featureCounts_out:
      need: true 
      outdir: distribution
      path: " "
      variables: 
        oname: "{outdir}/{project}.tsv"
      father:
        iname:
          - featureCounts
          - oname
      params:
        blank:
          - "cp {iname} {oname}"
          - "&& sed -i {oname} -e '2d' -e '1afeature\tChr\tStart\tEnd\tStrand\tLength\tReads' "
      
      outparams:
        oname: "{oname}"
      

  stat: 
    star_log:
      need: true 
      path: "python ~/scripts_ydx/extract_log_star.py"
      outdir: "stat"
      iparams_list:
        logs:
          - STAR
          - ologfinalout
          - ","
        projects:
          - raw
          - project
          - ","
      variables:
        oname: "{outdir}/mapping.stat.tsv"
      params:
        blank: 
          - "{logs}"
          - "{projects}"
          - "{oname}"
      
      outparams:
        omapping_stats: "{oname}"
      
    normalize_expression:
      need: true 
      path: " "
      outdir: "stat"
      iparams_list:
        intensities:
          - set_featureCounts_out
          - oname
          - ","
        projects:
          - raw
          - project
          - ","
      variables:
        method: "FPKM"
        oname_reads: "{outdir}/reads.stat.tsv"
        oname_intensity: "{outdir}/{method}.tsv"
        scripts_vstackfiles: "python ~/scripts_ydx/vstackfiles.py"
        scripts_normalize: "python ~/scripts_ydx/normaliseRNA_featureCounts.py"
      
      params:
        blank:
          - "{scripts_vstackfiles} {intensities} {projects} {oname_intensity} \n"
          - "{scripts_normalize} {method} {oname_reads} {oname_intensity} project \n"

